dist: xenial
language: node_js
node_js:
  - '10'

branches:
  except:
    - /^v[0-9]/

before_install:
  - npm i -g npm

install:
  - npm ci

script:
  - NODE_ENV=production npm run build
  - npm run test
  - node sample/demo-local.js
  # Test installation:
  - mkdir ~/libtest && cp ./sample/demo-lib.js ~/libtest/demo-lib.js && cd ~/libtest && npm install $TRAVIS_BUILD_DIR && node demo-lib.js 

jobs:
  include:
    - stage: deploy
      provider: script
      script: npx semantic-release
      skip_cleanup: true
      on:
        tags: false
        all_branches: true
      node_js: '10'
