dist: xenial
language: node_js
node_js:
  - '8'
  - '9'
  - '10'

before_install:
  - npm i -g npm

install:
  - npm ci

script:
  - NODE_ENV=production npm run build
  - npm run test
  - node sample/demo.js

jobs:
  include:
    - stage: deploy
      provider: script
      script: npx semantic-release
      skip_cleanup: true
      on:
        tags: false
        all_branches: true
      node_js: '10'

env:
  global:
    - secure: l20h48HCiBKrLnu70b4n1007kEPuCEjmz57JdHRT7pQOrdm6+K3oB/rTPiOSl8H09vsBJlF+OMdopFGHsCTp4P226R8vRlQyr9sh+ffk3kGfaYzEhNXFBN9NXSdatXBWnsBT2Y6/GmaPiWxalXQMbw22HgtENMjCscYqAOsXUKT1FyhOjOM5c+oALqgkeQxAZzOacmxjiST9zWudZ970uAzcYNbixxWVdQDfKycsRTmQKf5RpNVa4GW+/Hhv4fErtxDcrgeAdEsiAN2tLKvs3mnUrbvgiUlg49smsJOXMIpNqUWrcgGErfBjzZQH1w3n/2q1GNyse9AmNQDaJRtkU7vbo0wXNE25mlue/seMMofZo+DLXVgZ7HEv8adYsYYQ1mHK0ziO5EkEmLmXUfIbcOgwL0IXNvZyoyDIkDXshxtiVOm5pM5/9mHOzyNcVQvHETjIOhg4uyXu5r3unQULhrQtxjeOL0g085R+9pLA79FSDkrvzdtcbKtFGbCg8nMhs+bM0/K5Ty3rDI3kso+HILv7yFb+I23//8Sg56R9js4Y5HXcVZQ2rawMKclmIQym4ygPeExuEm6KuBBtqL0f5m7vCXH6J3GGCFY0zTArPG5nDHvHWdMYaCNDUUCwTxCDSrLH7nCz9N8visUMd72ZHN0MCK0C5iI+ECPFbehd3x0=
    - secure: mL9tNEPjeWGfF0z75fR47ljTl462VV3Be6q9udePxTUEs4z+CIg2qwv5VPM5gum6wjR69InljYjgW6VKjOJ27YIIHwd4mPwLIDvLSvAupmpu3J2yqYluUv1vzsX+Y1VdvgnMmtElZbvsY9gEFuJFfFWTaQelC14QnzUHKzxQnJyT2ziOftvI5LxuIpvWOnTrBogX1FDip5ZRxAv5ecDXBezwwAzbCv6O3s3PGA6G5XCfiOfTdl7b7NVQHTkopXakDeW56AlApBihkZoSq4gZ17x2kxw8dubeKaQi91CpCnwvzpiQq2UCUEzXJ0wqB7bTJKoi75FAZ++7MSZRC6y3eEhj1DNUfPdyrk56TjFKsOs41C1LCBiDMxn0hmgnW1UmHGOtka+TmInmO5rK+BzwTzd9J3xoNsCTr7Y0lhK4WXjZn3xtEZomtqPcBJFEU4cBy3Sk0WhIlzRV9IaS4KlUJ+Qo+xbxPV+UoBj1oXVlgZHrliBffRrXgoJ883tu4wWf1pfejvNGuh/Si/fWO2ISRPrrkdCbPBkijSdY8mTBS7JWkc8Or9ZIElPyCcQ4NNVIHqraPaPFznf6KVmMrRw2X5l6/OUIEr2nZCR6UhjAjjPalBciduXV+IZWweN+CGzWbfPZYsk7eT905QkLD9rHdGdbQJ4VRpeF8+8aJ2OHny4=
