# prettier-ignore

dist: xenial
language: node_js
node_js:
  - "8"
  - "9"
  - "10"

before_install:
  - npm i -g npm

install:
  - npm ci

script:
  - NODE_ENV=production npm run build
  - npm run test
  - node sample/demo.js

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
    node_js: "10"
